AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Hello World lambda

Resources:

  HelloWorldLambdaDev:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java11
      Timeout: 30
      Handler: com.muadmo.handler.HelloWorldHandler::handle
      MemorySize: 512
      CodeUri: target/helloWorldLambda-1.0-SNAPSHOT.zip
      AutoPublishAlias: dev
      Events:
        MyApiDev:
          Type: Api
          StageName: Dev
          Properties:
            Path: /
            Method: post
      Environment:
        Variables:
          NAME_TABLE: !Ref NameTableDev
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NameTableDev
<<<<<<< Updated upstream
=======
            
  HelloWorldGetNameLambdaDev:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.muadmo.handler.HelloWorldGetNameHandler::handle
      CodeUri: target/helloWorldLambda-1.0-SNAPSHOT.zip
      AutoPublishAlias: dev
      Events:
        MyApiDev:
          Type: Api
          StageName: Dev
          Properties:
            Path: /
            Method: get
      Environment:
        Variables:
          NAME_TABLE: !Ref NameTableDev
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NameTableDev

  HelloWorldGetAllNameLambdaDev:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.muadmo.handler.HelloWorldGetAllNameHandler::handle
      CodeUri: target/helloWorldLambda-1.0-SNAPSHOT.zip
      AutoPublishAlias: dev
      Events:
        MyApiDev:
          Type: Api
          StageName: Dev
          Properties:
            Path: /names
            Method: get
      Environment:
        Variables:
          NAME_TABLE: !Ref NameTableDev
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NameTableDev
>>>>>>> Stashed changes

  NameTableDev:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: nameId
        Type: String
        