AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: User template

Globals:
  Function:
    Runtime: java11
    MemorySize: 3008
    Timeout: 10
    
Resources:

  PostUserLambdaDev:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.muadmo.handler.MainHandler::route
      CodeUri: target/userLambda-1.0-SNAPSHOT.zip
      AutoPublishAlias: Dev
      Events:
        MyApiDev:
          Type: Api
          StageName: Dev
          Properties:
            Path: /users
            Method: post
      Environment:
        Variables:
          USER_TABLE: !Ref UserTableDev
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTableDev
            
  GetUserLambdaDev:
    Type: AWS::Serverless::Function
    Properties:
      Handler:  com.muadmo.handler.MainHandler::route
      CodeUri: target/userLambda-1.0-SNAPSHOT.zip
      AutoPublishAlias: Dev
      Events:
        MyApiDev:
          Type: Api
          StageName: Dev
          Properties:
            Path: /users/{nameId}
            Method: get
      Environment:
        Variables:
          USER_TABLE: !Ref UserTableDev
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTableDev

  GetAllUserLambdaDev:
    Type: AWS::Serverless::Function
    Properties:
      Handler:  com.muadmo.handler.MainHandler::route
      CodeUri: target/userLambda-1.0-SNAPSHOT.zip
      AutoPublishAlias: Dev
      Events:
        MyApiDev:
          Type: Api
          StageName: Dev
          Properties:
            Path: /users
            Method: get
      Environment:
        Variables:
          USER_TABLE: !Ref UserTableDev
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTableDev
            
  DeleteUserLambdaDev:
    Type: AWS::Serverless::Function
    Properties:
      Handler:  com.muadmo.handler.MainHandler::route
      CodeUri: target/userLambda-1.0-SNAPSHOT.zip
      AutoPublishAlias: Dev
      Events:
        MyApiDev:
          Type: Api
          StageName: Dev
          Properties:
            Path: /users/{nameId}
            Method: delete
      Environment:
        Variables:
          USER_TABLE: !Ref UserTableDev
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTableDev

  UpdateUserLambdaDev:
    Type: AWS::Serverless::Function
    Properties:
      Handler:  com.muadmo.handler.MainHandler::route
      CodeUri: target/userLambda-1.0-SNAPSHOT.zip
      AutoPublishAlias: Dev
      Events:
        MyApiDev:
          Type: Api
          StageName: Dev
          Properties:
            Path: /users/{nameId}
            Method: put
      Environment:
        Variables:
          USER_TABLE: !Ref UserTableDev
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTableDev

  UserTableDev:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: nameId
        Type: String
        