AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Hello World lambda

Globals:
  Function:
    Runtime: java11
    MemorySize: 512
    Timeout: 10
    
Resources:

  HelloWorldPostUserLambdaDev:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.muadmo.handler.HelloWorldPostUserHandler::handle
      CodeUri: target/helloWorldLambda-1.0-SNAPSHOT.zip
      AutoPublishAlias: dev
      Events:
        MyApiDev:
          Type: Api
          StageName: Dev
          Properties:
            Path: /users
            Method: post
      Environment:
        Variables:
          USER_TABLE: !Ref UserTableDev
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTableDev
            
  HelloWorldGetUserLambdaDev:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.muadmo.handler.HelloWorldGetUserHandler::handle
      CodeUri: target/helloWorldLambda-1.0-SNAPSHOT.zip
      AutoPublishAlias: dev
      Events:
        MyApiDev:
          Type: Api
          StageName: Dev
          Properties:
            Path: /
            Method: get
      Environment:
        Variables:
          USER_TABLE: !Ref UserTableDev
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTableDev

  HelloWorldGetAllUserLambdaDev:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.muadmo.handler.HelloWorldGetAllUserHandler::handle
      CodeUri: target/helloWorldLambda-1.0-SNAPSHOT.zip
      AutoPublishAlias: dev
      Events:
        MyApiDev:
          Type: Api
          StageName: Dev
          Properties:
            Path: /users
            Method: get
      Environment:
        Variables:
          USER_TABLE: !Ref UserTableDev
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTableDev
            
  HelloWorldDeleteUserLambdaDev:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.muadmo.handler.HelloWorldDeleteUserHandler::handle
      CodeUri: target/helloWorldLambda-1.0-SNAPSHOT.zip
      AutoPublishAlias: dev
      Events:
        MyApiDev:
          Type: Api
          StageName: Dev
          Properties:
            Path: /users/{nameId}
            Method: delete
      Environment:
        Variables:
          USER_TABLE: !Ref UserTableDev
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTableDev

  HelloWorldUpdateUserLambdaDev:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.muadmo.handler.HelloWorldUpdateUserHandler::handle
      CodeUri: target/helloWorldLambda-1.0-SNAPSHOT.zip
      AutoPublishAlias: dev
      Events:
        MyApiDev:
          Type: Api
          StageName: Dev
          Properties:
            Path: /users/{nameId}
            Method: put
      Environment:
        Variables:
          USER_TABLE: !Ref UserTableDev
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTableDev

  HelloWorldUpdateUserLambdaDev:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.muadmo.handler.HelloWorldUpdateUserHandler::handle
      CodeUri: target/helloWorldLambda-1.0-SNAPSHOT.zip
      AutoPublishAlias: dev
      Events:
        MyApiDev:
          Type: Api
          StageName: Dev
          Properties:
            Path: /users/{nameId}
            Method: put
      Environment:
        Variables:
          USER_TABLE: !Ref UserTableDev
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTableDev

  UserTableDev:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: nameId
        Type: String
        